# Generated by Django 3.0.6 on 2020-07-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
