# Generated by Django 3.0.6 on 2020-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usercustom_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='authenticated',
            field=models.BooleanField(default=0),
        ),
    ]
