# Generated by Django 2.2.6 on 2020-05-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='calendars.Day'),
        ),
    ]
