# Generated by Django 2.2.6 on 2020-05-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.TextField(default='#FFFFFF'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TextField(),
        ),
    ]
