# Generated by Django 2.2.12 on 2020-05-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200529_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start',
        ),
    ]
