# Generated by Django 2.2.12 on 2020-05-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200529_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
