# Generated by Django 3.0.6 on 2020-06-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='module',
        ),
    ]
