# Generated by Django 3.0.6 on 2020-06-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200619_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.TextField(default='#C95D63'),
        ),
        migrations.CreateModel(
            name='RepeatedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='repeated', to='events.EventGroup')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='repeated_event',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.RepeatedEvent'),
        ),
    ]
