# Generated by Django 3.0.7 on 2020-07-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('column', models.CharField(choices=[('todo', 'To Do'), ('onhold', 'On Hold'), (
                    'inprogress', 'In Progress'), ('done', 'Done')], max_length=10)),
                ('event_group', models.ForeignKey(blank=True, null=True,
                                                  on_delete=django.db.models.deletion.CASCADE, to='events.EventGroup')),
            ],
        ),
    ]
