# Generated by Django 3.0.7 on 2020-07-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200711_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='column',
            new_name='colid',
        ),
    ]
