# Generated by Django 3.0.7 on 2020-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200711_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='colid',
            new_name='column_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
