# Generated by Django 3.0.6 on 2020-06-07 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='user',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('index', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='month',
            unique_together={('month_name', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='year',
            unique_together={('index', 'user')},
        ),
    ]
