# Generated by Django 3.0.6 on 2020-07-15 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendars.Year'),
        ),
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calendars.Month'),
        ),
        migrations.AlterUniqueTogether(
            name='year',
            unique_together={('index', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='month',
            unique_together={('month_name', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('index', 'month')},
        ),
    ]
