# Generated by Django 3.0.6 on 2020-07-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20200624_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='is_leap',
            field=models.BooleanField(default=False),
        ),
    ]
