# Generated by Django 3.0.6 on 2020-07-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_month_is_leap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='is_leap',
        ),
        migrations.AddField(
            model_name='year',
            name='is_leap',
            field=models.BooleanField(default=False),
        ),
    ]
