# Generated by Django 3.0.7 on 2020-07-10 18:11

from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True,
                                            on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='events.EventGroup')),
            ],
            options={
                'unique_together': {('identifier', 'group')},
            },
        ),
        migrations.CreateModel(
            name='ImageHolder',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True,
                                            null=True, upload_to=upload.models.upload_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True,
                                            on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.EventGroup')),
            ],
            options={
                'unique_together': {('identifier', 'group')},
            },
        ),
        migrations.CreateModel(
            name='FileHolder',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True,
                                          upload_to=upload.models.upload_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True,
                                            on_delete=django.db.models.deletion.CASCADE, related_name='files', to='events.EventGroup')),
            ],
            options={
                'unique_together': {('identifier', 'group')},
            },
        ),
    ]
