# Generated by Django 3.0.6 on 2020-06-13 15:23

from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_module'),
        ('upload', '0002_auto_20200611_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=upload.models.upload_path)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.EventGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='fileholder',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fileholder',
            name='module',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.AddField(
            model_name='fileholder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.EventGroup'),
        ),
    ]
