# Generated by Django 3.0.6 on 2020-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200702_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
