# Generated by Django 3.0.6 on 2020-07-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_note_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='total',
        ),
    ]
