# Generated by Django 3.0.6 on 2020-06-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200615_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fileholder',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imageholder',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
