# Generated by Django 3.0.6 on 2020-07-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200627_2012'),
        ('upload', '0005_remove_note_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fileholder',
            unique_together={('identifier', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='imageholder',
            unique_together={('identifier', 'group')},
        ),
    ]
