# Generated by Django 3.0.6 on 2020-06-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200619_1613'),
        ('upload', '0005_auto_20200616_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileholder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='files', to='events.EventGroup'),
        ),
        migrations.AlterField(
            model_name='imageholder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='images', to='events.EventGroup'),
        ),
        migrations.DeleteModel(
            name='EventGroup',
        ),
    ]
