# Generated by Django 3.0.6 on 2020-06-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200619_1613'),
        ('upload', '0007_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
