# Generated by Django 3.0.6 on 2020-06-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20200621_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='identifier',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
