# Generated by Django 3.0.6 on 2020-06-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_note_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='identifier',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
