# Generated by Django 3.0.6 on 2020-06-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200619_1613'),
        ('upload', '0010_auto_20200623_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='identifier',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('identifier', 'group')},
        ),
    ]
