# Generated by Django 3.0.6 on 2020-06-29 05:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_path),
        ),
    ]
