# Generated by Django 3.0.6 on 2020-07-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercustom_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='total_notes',
            field=models.IntegerField(null=True),
        ),
    ]
