# Generated by Django 3.0.6 on 2020-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercustom_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='authenticated',
            field=models.IntegerField(default=0),
        ),
    ]
