# Generated by Django 3.0.6 on 2020-07-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usercustom_total_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='total_notes',
            field=models.IntegerField(default=0),
        ),
    ]
